apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.12.0 (0ab07be)
  creationTimestamp: null
  labels:
    io.kompose.service: golangapp
  name: golangapp
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: golangapp
    spec:
      containers:
      - args:
        - go
        - run
        - main.go
        image: golangapp
        name: golangapp
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
